TRUNCATE TABLE bounty RESTART IDENTITY;
insert into bounty (title,explain,solo_point,multi_point,solo_ticket,multi_ticket,cooldown) values ('BBQ01','Musou Howling Zinogre',15000,2000,10,3,0);
insert into bounty (title,explain,solo_point,multi_point,solo_ticket,multi_ticket,cooldown) values ('BBQ02','Musou Starving Jho',3000,1000,10,3,0);
insert into bounty (title,explain,solo_point,multi_point,solo_ticket,multi_ticket,cooldown) values ('BBQ03','Musou Blinking Narga',13000,1800,10,3,0);
insert into bounty (title,explain,solo_point,multi_point,solo_ticket,multi_ticket,cooldown) values ('BBQ04','HC Yian Unarmed',900,250,5,1,3);
insert into bounty (title,explain,solo_point,multi_point,solo_ticket,multi_ticket,cooldown) values ('BBQ05','HC Hermataur Unarmed',900,250,5,1,4);
insert into bounty (title,explain,solo_point,multi_point,solo_ticket,multi_ticket,cooldown) values ('BBQ06','HC Bright Hypnoc Unarmed',900,250,5,1,5);
insert into bounty (title,explain,solo_point,multi_point,solo_ticket,multi_ticket,cooldown) values ('BBQ07','Musou Elzelion',30000,30000,30,0,1);
insert into bounty (title,explain,solo_point,multi_point,solo_ticket,multi_ticket,cooldown) values ('BBQ08','GR Break Shagaru',1000,200,5,2,0);
insert into bounty (title,explain,solo_point,multi_point,solo_ticket,multi_ticket,cooldown) values ('BBQ09','GR Amatsu ',1000,200,5,2,3);
insert into bounty (title,explain,solo_point,multi_point,solo_ticket,multi_ticket,cooldown) values ('BBQ10','Musou Ruler Guanzuromu',3000,0,10,0,0);
insert into bounty (title,explain,solo_point,multi_point,solo_ticket,multi_ticket,cooldown) values ('BBQ11','Musou Bogabadorumu',15000,2000,15,0,2);
insert into bounty (title,explain,solo_point,multi_point,solo_ticket,multi_ticket,cooldown) values ('BBQ12','Diva Z4 Combo GiKheMi',5000,800,15,5,0);
insert into bounty (title,explain,solo_point,multi_point,solo_ticket,multi_ticket,cooldown) values ('BBQ13','Diva Z4 Combo GaHyuHyp',10000,2000,15,5,3);
insert into bounty (title,explain,solo_point,multi_point,solo_ticket,multi_ticket,cooldown) values ('BBQ14','Diva Exotic 5',5000,1000,10,3,2);
insert into bounty (title,explain,solo_point,multi_point,solo_ticket,multi_ticket,cooldown) values ('BBQ15','Wyvern Egg Delivery',0,0,3,0,1);
insert into bounty (title,explain,solo_point,multi_point,solo_ticket,multi_ticket,cooldown) values ('BBQ16','Berserk Extreme Raviante',10000,10000,20,20,1);
insert into bounty (title,explain,solo_point,multi_point,solo_ticket,multi_ticket,cooldown) values ('BBQ17','Caravan Origin Quest',5000,1000,10,3,2);
insert into bounty (title,explain,solo_point,multi_point,solo_ticket,multi_ticket,cooldown) values ('BBQ18','Mushou Zeruresu',15000,15000,15,0,3);
insert into bounty (title,explain,solo_point,multi_point,solo_ticket,multi_ticket,cooldown) values ('BBQ19','Caravan Burst Quest',5000,900,40,10,3);
insert into bounty (title,explain,solo_point,multi_point,solo_ticket,multi_ticket,cooldown) values ('BBQ20','Diva Z2 Combo GaRuTori',8000,1500,80,15,1);
insert into bounty (title,explain,solo_point,multi_point,solo_ticket,multi_ticket,cooldown) values ('SP','Floor 200 Multiplayer Road',0,0,20,20,1);
